name: Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc make

    - name: Build project
      run: |
        make

    - name: Check binary existence
      run: |
        if [ ! -f "push_swap" ]; then
          echo "Error: push_swap binary was not created!"
          exit 1
        fi
        echo "Binary successfully created."

    - name: Clean up
      run: |
        make fclean
        echo "Project cleaned successfully."
